/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:16626373-e29f-47cc-bdac-285659fc19f6",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_2C9H4B7z6",
    "aws_user_pools_web_client_id": "19e0jvbr7c53paa1697fda3qkt",
    "oauth": {}
};


export default awsmobile;
